### ISSUE TITLE
How to get good results

### ISSUE THREAD

**Issue by Tetsujinfr** [jswulff/mrflow#2]
I struggle to get some decent results on real life pictures/videos.
Blur looks like a significant issue bt maybe I a not using the algo properly. I am just usin the test syntax line from the readme so far.
Can you give some tweaks/advices to get better results if possible?

I attach the best test I got so far but I did expect some better rigidity map given the video you published a day ago.
![img2](https://user-images.githubusercontent.com/29961693/28296426-1f18384a-6b60-11e7-86ce-b95320c10610.jpg)
![img1](https://user-images.githubusercontent.com/29961693/28296448-41fe65f0-6b60-11e7-977b-830285861a3e.jpg)
![img3](https://user-images.githubusercontent.com/29961693/28296449-444d452e-6b60-11e7-92c8-778a3b335e03.jpg)
![comparison](https://user-images.githubusercontent.com/29961693/28296451-46c777de-6b60-11e7-9a12-c8c698585428.png)
![structure](https://user-images.githubusercontent.com/29961693/28296456-4e81df1e-6b60-11e7-9183-b1e8369f74d2.png)

**Comment by jswulff** [comment]
Hi Tets,

Do you use the `--noinit` switch? If so, please be aware that the results will be significantly worse than those in the paper, since no semantic segmentation is used at all.

To use the semantic segmentation, please provide a grayscale map using the `--rigidity RIGIDITYMAP.PNG`, where white denotes "static background with full certainty", and black denotes "object with full certainty". Such a map can be computed for example using a semantic segmentation CNN - the one we used will be online soon.

Second, in order to get much better accuracy, use DiscreteFlow as initialization instead of DeepFlow (which is what is used when you provide `--noinit`). Please see the `README.md` for details.

-Jonas

**Comment by Tetsujinfr** [comment]
Ok thanks. I dit use the --noinit flag yes, but I did not realize that the CNN segmentation piece was not provided in your code just yet. Now I understand better the gap with the paper results.

When do you think you will provide the CNN dev you used?

**Comment by jswulff** [comment]
Hi Tets,

The code is now available from here: http://files.is.tue.mpg.de/jwulff/mrflow/semantic_rigidity_cvpr2017.zip

Hope this helps!
-Jonas
